version: 0.2
 
env:
  variables:
    PROJECT_NAME: "WebGoat AWS"
    PROJECT_VERSION_NAME: "1.0"
  parameter-store:
    BLACKDUCK_URL: "Detect-BlackDuck-URL"
    BLACKDUCK_TOKEN: "Detect-BlackDuck-Token"
 
phases:
  install:
    commands:
      - curl -LOk https://detect.synopsys.com/detect8.sh
      - chmod +x ./detect8.sh
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - bash detect8.sh --blackduck.url=$BLACKDUCK_URL --blackduck.api.token=$BLACKDUCK_TOKEN --blackduck.trust.cert=true --blackduck.signature.scanner.individual.file.matching = ALL --blackduck.signature.scanner.snippet.matching = FULL_SNIPPET_MATCHING --blackduck.signature.scanner.upload.source.mode = true --detector.search.depth = 100 --detect.project.name=$PROJECT_NAME --detect.project.version.name=$PROJECT_VERSION_NAME
  
artifacts:
  discard-paths: yes
