version: 0.2
 
env:
  variables:
    PROJECT_NAME: "WebGoat_AWS"
    PROJECT_VERSION_NAME: "1.0"
  parameter-store:
    BLACKDUCK_URL: "Detect-BlackDuck-URL"
    BLACKDUCK_TOKEN: "Detect-BlackDuck-Token"
 
phases:
  install:
    commands:
      - curl -LOk https://detect.synopsys.com/detect8.sh
      - chmod +x ./detect8.sh
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - bash detect8.sh --blacproject.version.name=$PROJECT_VERSION_NAME
  
artifacts:
  discard-paths: yes
